CREATE TABLE `sys_user` (
                            `id` bigint(20) NOT NULL COMMENT '主键编码',
                            `user_key` varchar(64) NOT NULL COMMENT '用户标识',
                            `main_key` varchar(64) DEFAULT NULL COMMENT '主用户标识',
                            `user_no` varchar(64) DEFAULT NULL COMMENT '用户编号',
                            `user_name` varchar(64) DEFAULT NULL COMMENT '用户名称',
                            `password` varchar(64) DEFAULT NULL COMMENT '密码',
                            `user_flag` varchar(20) DEFAULT NULL COMMENT '用户标记',
                            `user_type` varchar(16) DEFAULT NULL COMMENT '用户类型',
                            `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '用户状态',
                            `phone_num` varchar(16) NOT NULL DEFAULT '' COMMENT '手机号',
                            `real_name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
                            `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '昵称',
                            `email` varchar(32) NOT NULL DEFAULT '' COMMENT '邮箱',
                            `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '头像地址',
                            `birthday` timestamp NULL DEFAULT NULL COMMENT '出生日期',
                            `start_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
                            `end_time` datetime DEFAULT '2100-12-21 23:59:59' COMMENT '结束时间',
                            `gender_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别',
                            `owner_id` varchar(16) DEFAULT 'DEFAULT' COMMENT '所有者编码',
                            `external_code` varchar(64) DEFAULT NULL COMMENT '第三方用户唯一标识',
                            `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                            `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                            `remark` varchar(255) DEFAULT NULL COMMENT '说明',
                            `qr_code` varchar(255) DEFAULT NULL COMMENT '二维码',
                            `lun_id` varchar(64) DEFAULT NULL COMMENT 'EHR同步过来的数据主键',
                            PRIMARY KEY (`id`) USING BTREE,
                            UNIQUE KEY `uk_userkey` (`user_key`) USING BTREE,
                            UNIQUE KEY `uk_user_name` (`user_name`),
                            KEY `idx_phonenum` (`phone_num`) USING BTREE,
                            KEY `idx_external_code` (`external_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='b端用户';